### ISSUE TITLE
如何同步更新包

### ISSUE THREAD

**Issue by WGLKing** [cnpm/cnpmweb#15]

**Comment by DevDengChao** [comment]
![QQ截图20230817143318](https://github.com/cnpm/cnpmweb/assets/16363180/9801f3e7-1e0d-4141-8617-671f9ddd2ed1)

我也是找了半天才找到, 现在的同步按钮在版本列表里, 希望后续在包的首页能加一个按钮吧.

**Comment by WGLKing** [comment]
> ![QQ截图20230817143318](https://user-images.githubusercontent.com/16363180/261219601-9801f3e7-1e0d-4141-8617-671f9ddd2ed1.png)
> 
> 我也是找了半天才找到, 现在的同步按钮在版本列表里, 希望后续在包的首页能加一个按钮吧.

好的感谢 ！现在拉取好像有问题  希望官方能尽快解决

**Comment by fengmk2** [comment]
@elrrrrrrr 首页加上？

**Comment by elrrrrrrr** [comment]
ref: https://github.com/cnpm/cnpmweb/pull/17

😄 加上啦，github 出 bug 了，https://github.com/cnpm/cnpmweb/issues/15 关联不到 issue 了

**Comment by Clleej** [comment]
> > ![QQ截图20230817143318](https://user-images.githubusercontent.com/16363180/261219601-9801f3e7-1e0d-4141-8617-671f9ddd2ed1.png)
> > 我也是找了半天才找到, 现在的同步按钮在版本列表里, 希望后续在包的首页能加一个按钮吧.
> 
> 好的感谢 ！现在拉取好像有问题 希望官方能尽快解决

遇到了相同问题，拉不到最新的alpha版本
