### ISSUE TITLE
搜索antd-pro-schema-form包点击搜索按钮没反应？

### ISSUE THREAD

**Issue by drdevelop** [cnpm/cnpmweb#27]
<img width="1016" alt="Screen Shot 2023-08-22 at 11 12 17 PM" src="https://github.com/cnpm/cnpmweb/assets/39514265/18823dee-2cdc-4e74-a712-fdaf47815b11">

**Comment by elrrrrrrr** [comment]
目前确实还没实现 😭

![image](https://github.com/cnpm/cnpmweb/assets/5574625/5a453c25-6e36-47e5-8e2e-95f0341c6074)

近期我们会将搜索服务切换至 cnpmcore 内 https://github.com/cnpm/cnpmcore/pull/513

功能迁移后再做搜索结果页面

**Comment by drdevelop** [comment]
好的，了解了

**Comment by elrrrrrrr** [comment]
😄 @drdevelop  
搜索已经切换到了 cnpmcore 内置服务啦，速度会快很多。

搜索结果页也来啦
