### ISSUE TITLE
缺个跳转首页

### ISSUE THREAD

**Issue by crazyair** [cnpm/cnpmweb#41]
在任何包的详情页没办法返回首页

![image](https://github.com/cnpm/cnpmweb/assets/7971419/f961b08d-2814-4fc9-9101-474066f565b6)

**Comment by fengmk2** [comment]
左上角的 logo 可以回首页 
![image](https://github.com/cnpm/cnpmweb/assets/156269/0de1a486-125e-4951-a1dc-e5f3be592f8c)

**Comment by crazyair** [comment]
这应该是设计问题了，logo 跟 glob 挨得太近了，会被理解为 glob 的 logo，需要增大间隙，让他为不相干的 2 个元素

**Comment by fengmk2** [comment]
可以来个 pr
