### ISSUE TITLE
在搜索后单击跳转后无法进入详情页

### ISSUE THREAD

**Issue by undefined-hestudio** [cnpm/cnpmweb#44]
进入时提示`Network response was not ok`

https://github.com/cnpm/cnpmweb/assets/119711513/e5c0f216-5482-44ad-bbf6-7c0dbc34db95

**Comment by elrrrrrrr** [comment]
@undefined-hestudio 
可能是查询 manfiest 失败的原因，现在通过静态化方案应该已经解决了这个问题。


https://github.com/cnpm/cnpmweb/assets/5574625/dd352d15-fa84-4261-980b-c2a335131194

**Comment by elrrrrrrr** [comment]
感谢反馈，我将暂时关闭这个 issue。
如果有其他问题请随时反馈或者 reopen 这个 issue。
