### ISSUE TITLE
部分 package 详情页面布局有问题

### ISSUE THREAD

**Issue by dancerphil** [cnpm/cnpmweb#57]
错误页面以及截图

https://npmmirror.com/package/@panda-design/components?version=0.0.64

Mac + Chrome 119

<img width="1440" alt="image" src="https://github.com/cnpm/cnpmweb/assets/7264444/887d24ca-3cb4-4f72-b60d-87e0296a567c">

期望

<img width="1440" alt="image" src="https://github.com/cnpm/cnpmweb/assets/7264444/ae4b9dc2-fe79-4fd7-ab91-4f1a5eb656ca">

**Comment by elrrrrrrr** [comment]
@dancerphil 
感谢反馈，布局和兼容性真是永恒的难题 😭
看上去你已经找到了解决的办法，要不要直接提交 pr 修复一下 😄

**Comment by dancerphil** [comment]
> @dancerphil 感谢反馈，布局和兼容性真是永恒的难题 😭 看上去你已经找到了解决的办法，要不要直接提交 pr 修复一下 😄

我就发现有的左右，有的上下，没仔细看原因😅

**Comment by fengmk2** [comment]
closes by https://github.com/cnpm/cnpmweb/pull/61
