### ISSUE TITLE
希望点击首页，地址栏的版本号可以去掉

### ISSUE THREAD

**Issue by chenbimo** [cnpm/cnpmweb#60]
![image](https://github.com/cnpm/cnpmweb/assets/33003566/08af17b1-b147-4450-a5ee-862e18156e40)

如图，希望点击首页的时候，可以回到不带版本号的页面显示。

**Comment by elrrrrrrr** [comment]
目前首页会根据不同版本号来展示对应 readme 的内容 🤔

**Comment by yoyo837** [comment]
> 目前首页会根据不同版本号来展示对应 readme 的内容 🤔

没有版本号的时候取 latest 的版本来显示

**Comment by yoyo837** [comment]
我看现在就是这样实现的

**Comment by elrrrrrrr** [comment]
@chenbimo  看看预期交互是多少呀？

**Comment by elrrrrrrr** [comment]
我将暂时关闭归档这个 issue，如果有信息更新再 reopen 哈 🙏🏻
