### ISSUE TITLE
[Feature Request]: `/versions` url-props 添加 "正式版本" 与 "所有版本"

### ISSUE THREAD

**Issue by Zhengqbbb** [cnpm/cnpmweb#63]
### 需求：
希望可以有一个直接的 url 展示源的所有版本信息

### 当前：
在 `package/${pkg}/versions` 页面中选项卡 "正式版本" 与 "所有版本" 在点击后 url 没有发生变化

### 可能的实现方案
- 在 npm 当前使用 url props 进行标识 `?activeTab=versions` 来控制选项卡的显示
- e.g https://www.npmjs.com/package/czg?activeTab=versions

<img width="1624" alt="image" src="https://github.com/cnpm/cnpmweb/assets/40693636/520c7664-f07e-4d7e-b7b3-e633a8a95d62">

**Comment by elrrrrrrr** [comment]
👌🏻 加个 query 参数来控制，默认记在 localStorage 里

**Comment by Zhengqbbb** [comment]
好像引入了新的 Bug 😶‍🌫️

https://github.com/cnpm/cnpmweb/assets/40693636/b7dd5551-9c0a-42a1-a7f0-c17958fc4ad5
