### ISSUE TITLE
[Bug Report]: 点击版本选项卡后，会发生过滤页面数据异常

### ISSUE THREAD

**Issue by Zhengqbbb** [cnpm/cnpmweb#66]
重现步骤：
1. https://npmmirror.com/package/czg/home 首页点击 “查看全部” 版本
2. 我的这个包有一些 beta 版本号，在点击 “版本记录” - “所有版本” & “当前 Tags” - “所有版本” 后出现列表闪动，列表从正常的显示数据变化为错误的显示数据
3. url query param 正常发生变化 `?versions=all&tags=all`

初步怀疑是列表过滤与 url props 的改变进行渲染碰撞导致

---

https://github.com/cnpm/cnpmweb/assets/40693636/b7dd5551-9c0a-42a1-a7f0-c17958fc4ad5

_Originally posted by @Zhengqbbb in https://github.com/cnpm/cnpmweb/issues/63#issuecomment-1862007736_

**Comment by fengmk2** [comment]
@elrrrrrrr

**Comment by elrrrrrrr** [comment]
组件之前没有替换成受控模式 可能会有渲染不一致情况出现
另外 router.isReady 可能也有影响 不过我本地还没有重现出来
部署之后再验证看看 🙏🏻
