### ISSUE TITLE
NpmVersionSelect 组件中对版本排序方法sortNodes有问题

### ISSUE THREAD

**Issue by liuyq1209** [cnpm/cnpmweb#71]
['1.0.85-beta.240124.151613','1.0.85-beta.240124.150810'] , 两个版本排序后 '151613' 被排在‘150810’后面了，应该排在前面

**Comment by elrrrrrrr** [comment]
@liuyq1209 麻烦提供个能重现的 url 地址 🙏🏻

**Comment by elrrrrrrr** [comment]
@liuyq1209 😄 看着已经定位到了具体问题 有兴趣直接 pr 修复下吗

**Comment by liuyq1209** [comment]
> @liuyq1209 😄 看着已经定位到了具体问题 有兴趣直接 pr 修复下吗

官方侧有修复计划吗
