### ISSUE TITLE
无法同步Npm官方源上删除的包和注销的用户。

### ISSUE THREAD

**Issue by yeying-xingchen** [cnpm/cnpmweb#79]
无法同步Npm官方源上删除的包和注销的用户。

**Comment by elrrrrrrr** [comment]
目前 cnpm 会默认 follow 上游 registry 的删包操作，这通常是由于安全风险或开发者个人意愿。
此外，我们在 cnpmcore 中提供 [block 或 ignore 模式](https://github.com/cnpm/cnpmcore/blob/master/app/common/constants.ts#L17)，在私有部署场景，管理员手动恢复。

**Comment by elrrrrrrr** [comment]
关于 cnpmcore 部署相关配置可以参考 [ref](https://github.com/cnpm/cnpmcore/issues/664)

**Comment by elrrrrrrr** [comment]
@Yeying-Xingchen  我将暂时关闭这个 issue ，如果还有其他问题可以继续留言 reopen 🙏🏻
